POST http://localhost:8080/map/getpath HTTP/1.1
content-type: application/json

{
    "pointa":[89.646781,27.429890],
    "pointb":[89.637372,27.465511]
    }
}

# GET http://localhost:8080/map/searchaddress/gochukhalam63
